### ISSUE TITLE
Hi tango question

### ISSUE THREAD

**Issue by withJack** [bfosso/MetaShot#11]
Hi 
Currently, I'm trying to go over your program. 
I got stuck running MetaShot.

(metashot) sjlee@mine:/data/sjlee/labwork/MetaShot/MetaShot:> python MetaShot_Master_script.py -m simulated_list.txt -p parameters_file.txt 
['/data/sjlee/labwork/MetaShot/simulated/simulated_metagenome_1.fastq', '/data/sjlee/labwork/MetaShot/simulated/simulated_metagenome_2.fastq']
/data/sjlee/labwork/MetaShot/MetaShot/
/data/sjlee/labwork/MetaShot/MetaShot_reference_data/
/data/sjlee/labwork/MetaShot/MetaShot_reference_data/Bacteria/bacterial_bowtie_index_reference.lst
Cleaning data
Traceback (most recent call last):
  File "MetaShot_Master_script.py", line 292, in <module>
    p = subprocess.Popen(cmd, stdout=std_out_file, stderr=std_out_file)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I'm assuming it is because there are no tango related files (folders)
'Virus/tango_dmp_folder/'
'Bacteria/tango_dmp_folder/',
'Fungi/tango_dmp_folder/' ,
'Protist/tango_dmp_folder/'

Am I supposed to run tango.pl in 'New_TANGO_perl_version' folder? 
If it is, can give some command lines for guidance or perhaps the preprocessed files you used?

Thanks a lot.

**Comment by bfosso** [comment]
Hi, thanks for your interest in MetaShot.
It seems the error has happened during FaQCs execution. Have you installed all the required packages?

**Comment by withJack** [comment]
Thanks for the fast response.

I believe i have.. my FaQCs version is 1.34. 
You don't think it's tango_dmp_folder problem? 

Oops I forgot to add FaQCs in the $PATH. 
But it still won't work.. 

['/data/sjlee/labwork/MetaShot/simulated/simulated_metagenome_1.fastq', '/data/sjlee/labwork/MetaShot/simulated/simulated_metagenome_2.fastq']
/data/sjlee/labwork/MetaShot/MetaShot/
/data/sjlee/labwork/MetaShot/MetaShot_reference_data/
/data/sjlee/labwork/MetaShot/MetaShot_reference_data/Bacteria/bacterial_bowtie_index_reference.lst
Cleaning data
file /data/sjlee/labwork/MetaShot/MetaShot/trimmed_data_1/QC.1.trimmed.fastq is missing

..

**Comment by withJack** [comment]
The following is the 'faqcs_stdout.out' file   

1 Unknown option: 1
  2 Unknown option: 2
  3 
  4  Missing input files.
  5 
  6  perl /data/sjlee/labwork/MetaShot/metashot_env/bin/FaQCs [options] [-u unpaired.fastq] -p reads1.fastq reads2.fastq -d out_directory
  7 
  8  Option -h to see full usage

**Comment by bfosso** [comment]
It seems there are some issues with the FaQCs command line. I've to check that to verify if it is related to the version you're using. Currently I'm writing from my phone, so in the meanwhile you may try to upgrade your FaQCs versione.

**Comment by withJack** [comment]
Hi, after upgrading my FaQCs version to 2.09, the program seemed to run well for a while (2 days or so).
However, at the end i've got an error shown below.

['/data/sjlee/labwork/MetaShot/simulated/simulated_metagenome_1.fastq', '/data/sjlee/labwork/MetaShot/simulated/simulated_metagenome_2.fastq']
/data/sjlee/labwork/MetaShot/MetaShot/
/data/sjlee/labwork/MetaShot/MetaShot_reference_data/
/data/sjlee/labwork/MetaShot/MetaShot_reference_data/Bacteria/bacterial_bowtie_index_reference.lst
Cleaning data
correctly formatted read_list file
fastq control
QC.1.trimmed.fastq
QC.2.trimmed.fastq
START 13/07/2020 10:19:18
 vTraceback (most recent call last):
  File "/data/sjlee/labwork/MetaShot/MetaShot/find_microbiome.py", line 222, in <module>
    process_status = pid_status(proc_id)
  File "/data/sjlee/labwork/MetaShot/MetaShot/find_microbiome.py", line 127, in pid_status
    status = psutil.Process(process_pid).status()
  File "/home/sjlee/.local/lib/python2.7/site-packages/psutil/__init__.py", line 346, in __init__
    self._init(pid)
  File "/home/sjlee/.local/lib/python2.7/site-packages/psutil/__init__.py", line 373, in _init
    self.create_time()
  File "/home/sjlee/.local/lib/python2.7/site-packages/psutil/__init__.py", line 723, in create_time
    self._create_time = self._proc.create_time()
  File "/home/sjlee/.local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1516, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/sjlee/.local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1728, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/home/sjlee/.local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1516, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/sjlee/.local/lib/python2.7/site-packages/psutil/_common.py", line 452, in wrapper
    return fun(self)
  File "/home/sjlee/.local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1558, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/home/sjlee/.local/lib/python2.7/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
IOError: [Errno 2] No such file or directory: '/proc/92745/stat'
in your sample there are not microbial candidates

Does this mean there are no microbial candidates? or it's an error?

Thanks

**Comment by withJack** [comment]
I've used the simulated data file, you put up in the cloud.

**Comment by bfosso** [comment]
Actually it seems that it fails to track bowtie2 processes. Please verify if the same files were written.

**Comment by withJack** [comment]
Sorry for keep on bothering you.. 
I think i've fixed the bowtie2 process problem. 
Somehow one of the Bacteria reference folder name was wrong.

 ['/data/sjlee/labwork/MetaShot/simulated/simulated_metagenome_1.fastq', '/data/sjlee/labwork/MetaShot/simulated/simulated_metagenome_2.fastq']
/data/sjlee/labwork/MetaShot/MetaShot/
/data/sjlee/labwork/MetaShot/MetaShot_reference_data/
/data/sjlee/labwork/MetaShot/MetaShot_reference_data/Bacteria/bacterial_bowtie_index_reference.lst
Cleaning data
correctly formatted read_list file
fastq control
QC.1.trimmed.fastq
QC.2.trimmed.fastq
START 15/07/2020 18:44:45
PE da mappare 0
END 15/07/2020 18:46:32
in your sample there are not microbial candidates

Does this result look familiar to you? 

By the way, I've downloaded the simulated benchmark data from this URL.
https://recascloud.ba.infn.it/index.php/s/nw4s9hqnF8QkBsK

**Comment by bfosso** [comment]
Actually the results you've obtained are quite unexpected. Considering all the steps performed in MetaShot is surely impossible it takes only 2 minutes to complete all the stuffs. Are you sure Bowtie2 is working?
