### ISSUE TITLE
MetaShot Application to Environmental Samples

### ISSUE THREAD

**Issue by cam315** [bfosso/MetaShot#2]
@bfosso As described in the Readme file, the tool package is designed for Human gut microbiome, I was wondering whether you have tested the pipeline with environmental samples? I would assume this is applicable, but need to use a more comprehensive reference database. Could you please give me some instruction in more detail?
Thank you.

**Comment by bfosso** [comment]
Actually the MetaShot reference collection covers all the prokaryotes, viral and protist sequences available when I created them (about one years ago, the updating process is really slow and  we are working on it).
We tested the pipeline against a viral and bacterial mock communities and even if it works really well I think that you need to modify the Master script by commenting the host section.

**Comment by cam315** [comment]
Thank you for your reply. For the modification you mentioned, could you please give me more instruction?

**Comment by bfosso** [comment]
I will prepare a Master script version for non human microbiome usage.

**Comment by bfosso** [comment]
I've added the -e option to the MetaShot_Master_script.py to exclude the comparison with the human genome. It is a simple walk around to avoid the STAR execution and maintain the general workflow.
