### ISSUE TITLE
DIrect link to reference collections?

### ISSUE THREAD

**Issue by transcript** [bfosso/MetaShot#6]
Hello,

For the reference collections download, there doesn't seem to be a direct file path, which means it can't be downloaded using wget.  The "direct link" is just https://recascloud.ba.infn.it/index.php/s/9dFFTJUr0bOU2mN/download, which isn't the file itself.

Is there a direct path?

**Comment by bfosso** [comment]
Please type:

_wget --no-check-certificate https://recascloud.ba.infn.it/index.php/s/9dFFTJUr0bOU2mN/download_

It will generate a file called **download** of approximately 49 Gb. 
Following type:

_tar -xvfz dowload_
