### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by lmanchon** [bfosso/MetaShot#7]
--Hi,

some files and folders below are missing from compressed folder “MetaShot_reference_data.tar.gz”:
 'visualization_virus.dmp',
 'VIRUS_DMP', 
'Bacteria/tango_dmp_folder', 
'Fungi/tango_dmp_folder/' , 
Protist/tango_dmp_folder

can you check that please ?

Thak you --

**Comment by bfosso** [comment]
I've checked and all the required files are available in the package.

**Comment by lmanchon** [comment]
impossible to check without md5 file

**Comment by bfosso** [comment]
As explained in the "**MetaShot User Guide**", the expected Md5sum for the references folder is: **2def0475c8c3b49c15181de0c226b11a**
So you can verify your file by taping: 
_md5sum MetaShot_reference_data.tar.gz_

**Comment by lmanchon** [comment]
md5sum MetaShot_reference_data.tar.gz
04ed80dc764bc071281272cfe8bdd0bb  MetaShot_reference_data.tar.gz

**Comment by bfosso** [comment]
Could you please attach the link used to download the files?

**Comment by lmanchon** [comment]
--Hi,
i made a mistake, i have checked the md5 and it's correct.
in the parameter you use -s DNA: MetaShot_Master_script.py -p param_file.txt -m read_files -s DNA
what does it mean ?
 thank you --

**Comment by lmanchon** [comment]
pipeline failed when trimmed file is missing:

['/microbiome/RAW_DATA/ABX-63_R1.fastq.gz', '/microbiome/RAW_DATA/ABX-63_R2.fastq.gz']
/home/MetaShot/MetaShot_reference_data/Bacteria/bacterial_bowtie_index_reference.lst
file /home/MetaShot/trimmed_data_1/QC.1.trimmed.fastq is missing

Also I used paired-end files but faqcs_stdout.out tell me not:
The seqeucne names of the paired end reads in /home/MetaShot/phix_removal_1/R1_no_phix.fastq,/home/MetaShot/phix_removal_1/R2_no_phix.fastq are not matching.
Will use them as single end reads
Bwa extension trimming algorithm is used.
Processing /home/MetaShot/phix_removal_1/R1_no_phix.fastq file
Processed 107699/1107699
 Post Trimming Length(Mean, Std, Median, Max, Min) of 107633 reads with Overall quality 38.43
 (146.24, 13.18, 151.0, 151, 50)
Processed 1107699/1107699
 Post Trimming Length(Mean, Std, Median, Max, Min) of 999312 reads with Overall quality 38.18
 (145.04, 14.67, 151.0, 151, 50)
Processing /home/MetaShot/phix_removal_1/R2_no_phix.fastq file
Processed 1215398/2215398
 Post Trimming Length(Mean, Std, Median, Max, Min) of 107285 reads with Overall quality 36.85
 (135.65, 24.94, 150.0, 151, 50)
Processed 2215398/2215398
 Post Trimming Length(Mean, Std, Median, Max, Min) of 996218 reads with Overall quality 36.74
 (131.54, 26.29, 148.0, 151, 50)

**Comment by bfosso** [comment]
The pipeline requires the trimmed file to procede and it is designed to work with PE reads. 
Have you checked your files are PE?

**Comment by lmanchon** [comment]
absolutly, my PE files were before well corrected by bbmap/repair.sh

**Comment by lmanchon** [comment]
this problem is over.
you can close this ticket.
