### ISSUE TITLE
find_microbiome.py failed when running process on cluster node

### ISSUE THREAD

**Issue by lmanchon** [bfosso/MetaShot#9]
running on node-02 at mardi 19 février 2019, 21:05:37 (UTC+0100)
================================================================
276458 running
correctly formatted read_list file
fastq control
QC.1.trimmed.fastq
QC.2.trimmed.fastq
START 19/02/2019 21:33:16
Traceback (most recent call last):
  File "/home/MetaShot/find_microbiome.py", line 220, in <module>
    process_status = pid_status( proc_id )
  File "/home/MetaShot/find_microbiome.py", line 126, in pid_status
    status = psutil.Process( process_pid ).status( )
  File "/home/PSUTIL/lib/python/psutil-5.5.0-py2.7-linux-x86_64.egg/psutil/__init__.py", line 773, in status
    return self._proc.status()
  File "/home/PSUTIL/lib/python/psutil-5.5.0-py2.7-linux-x86_64.egg/psutil/_pslinux.py", line 1525, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=35159)
Feb 19 21:58:40 ..... started STAR run
Feb 19 21:58:43 ..... loading genome
Feb 19 22:07:59 ..... started STAR run
Feb 19 22:07:59 ..... loading genome
Feb 19 22:07:59 ..... started mapping
Feb 19 22:12:50 ..... finished successfully
correctly formatted read_list file
Mapping on the genome
sam parsing
HOST MAPPING IS DONE
Feb 19 22:12:53 ..... started STAR run
Feb 19 22:12:53 ..... loading genome
the indicated /home/MetaShot/trimmed_data_1/R1_micro_candidates.fastq fastq file doesn't exist
This script works in two different steps:
        (1) it maps the sequencing data against the Bacterial division;
        (2) it extract the mapped pairs and tries to map them on the human reference;
Options:
        -i      paired-end file list: a line containing the R1, the R2 files [MANDATORY]
        -p      Number of threads/processors available [MANDATORY]      -r      reference path [MANDATORY]
        -s      script path path [MANDATORY]
        -h      print this help.
Usage:
        python division_analyser -i read_list

the process is still running or frozen on the node.

**Comment by bfosso** [comment]
Actually Metashot is not designed to work on cluster. Consequently it is not able to map the process across different nodes.

**Comment by lmanchon** [comment]
that's what I thought when I looked at the error returns from psutil
